# Use this file to templatize your application's native configuration files.
# See the docs at https://www.habitat.sh/docs/create-packages-configure/.

read_data_path = "__PATH__executable__/../../data"
write_data_path = "/hab/svc/factorio/data"

# [general]
locale=""

# [other]
# Options: true, false
verbose-logging="false"
# Options: true, false
log-saving-statistics="false"
autosave-interval="5"
autosave-slots="3"
minimum-latency-in-multiplayer="0"
port="34197"
max-map-preview-chunk-side="64"
proxy=""
proxy-username=""
proxy-password=""
# Options: true, false
check-updates="true"
# Options: true, false
enable-experimental-updates="false"
# Options: true, false
enable-new-mods="true"
# Options: true, false
use-mod-settings-per-save="true"
# Options: true, false
disable-minimal-mode="false"
# Options: true, false
enable-razer-chroma-support="true"
# Options: true, false
enable-crash-log-uploading="true"
# Options: true, false
enable-heap-validation="true"
# Options: true, false
non-blocking-saving="false"
# Options: fast, maximum
multiplayer-compression-level="fast"
# Options: none, fast, maximum
autosave-compression-level="fast"

# [sound]
master-volume="0.600000"
music-volume="0.400000"
game-effects-volume="0.700000"
gui-effects-volume="0.700000"
walking-sound-volume="0.300000"
environment-sounds-volume="0.450000"
alerts-volume="0.550000"
audible-distance="40.000000"
environment-audible-distance="15.000000"
maximum-environment-sounds="15"
active-gui-volume-modifier="1.300000"
active-gui-environment-volume-modifier="0.600000"
ambient-music-pause-mean-seconds="45.000000"
ambient-music-pause-variance-seconds="30.000000"
# Options: main-tracks-only, interleave-main-tracks-with-interludes, randomize-all
ambient-music-mode="interleave-main-tracks-with-interludes"

# [map-view]
# Options: true, false
show-logistic-network="false"
# Options: true, false
show-electric-network="false"
# Options: true, false
show-turret-range="false"
# Options: true, false
show-pollution="true"
# Options: true, false
show-train-station-names="true"
# Options: true, false
show-player-names="true"
# Options: true, false
show-networkless-logistic-members="false"
# Options: true, false
show-non-standard-map-info="false"

# [debug]
force="enemy"
# Options: always, basic, detailed, full, never
show-fps="basic"
# Options: always, basic, detailed, full, never
show-detailed-info="basic"
# Options: always, basic, detailed, full, never
show-tile-properties-in-detailed-info="basic"
# Options: always, basic, detailed, full, never
show-time-usage="basic"
# Options: always, basic, detailed, full, never
show-sprite-counts="detailed"
# Options: always, basic, detailed, full, never
show-multiplayer-waiting-icon="basic"
# Options: always, basic, detailed, full, never
show-multiplayer-statistics="basic"
# Options: always, basic, detailed, full, never
show-multiplayer-selection-rectangles="detailed"
# Options: always, basic, detailed, full, never
show-tile-grid="full"
# Options: always, basic, detailed, full, never
show-collision-rectangles="detailed"
# Options: always, basic, detailed, full, never
show-selection-rectangles="detailed"
# Options: always, basic, detailed, full, never
show-paths="full"
# Options: always, basic, detailed, full, never
show-path-requests="full"
# Options: always, basic, detailed, full, never
show-next-waypoint-bb="full"
# Options: always, basic, detailed, full, never
show-target="full"
# Options: always, basic, detailed, full, never
show-unit-group-info="full"
# Options: always, basic, detailed, full, never
show-unit-behavior-info="full"
# Options: always, basic, detailed, full, never
show-last-path-detail="full"
# Options: always, basic, detailed, full, never
show-path-cache="full"
# Options: always, basic, detailed, full, never
show-path-cache-paths="full"
# Options: always, basic, detailed, full, never
show-rail-paths="full"
# Options: always, basic, detailed, full, never
show-rolling-stock-count="full"
# Options: always, basic, detailed, full, never
show-rail-connections="detailed"
# Options: always, basic, detailed, full, never
show-rail-joints="detailed"
# Options: always, basic, detailed, full, never
show-rail-signal-states="full"
# Options: always, basic, detailed, full, never
show-train-stop-point="detailed"
# Options: always, basic, detailed, full, never
show-train-braking-distance="full"
# Options: always, basic, detailed, full, never
show-train-signals="full"
# Options: always, basic, detailed, full, never
show-network-connected-entities="detailed"
# Options: always, basic, detailed, full, never
show-circuit-network-numbers="detailed"
# Options: always, basic, detailed, full, never
show-energy-sources-networks="detailed"
# Options: always, basic, detailed, full, never
show-active-state="detailed"
# Options: always, basic, detailed, full, never
show-wakeup-lists="detailed"
# Options: always, basic, detailed, full, never
show-transport-lines="detailed"
# Options: always, basic, detailed, full, never
show-transport-line-gaps="detailed"
# Options: always, basic, detailed, full, never
show-pollution-values="full"
# Options: always, basic, detailed, full, never
show-active-entities-on-chunk-counts="full"
# Options: always, basic, detailed, full, never
show-active-chunks="full"
# Options: always, basic, detailed, full, never
show-polluted-chunks="full"
# Options: always, basic, detailed, full, never
show-enemy-expansion-candidate-chunks="full"
# Options: always, basic, detailed, full, never
show-enemy-expansion-candidate-chunk-values="full"
# Options: always, basic, detailed, full, never
show-bad-attack-chunks="full"
# Options: always, basic, detailed, full, never
show-tile-variations="full"
# Options: always, basic, detailed, full, never
show-raw-tile-transitions="never"
# Options: always, basic, detailed, full, never
show-tile-correction-previews="never"
# Options: always, basic, detailed, full, never
show-fluid-box-fluid-info="detailed"
# Options: always, basic, detailed, full, never
show-environment-sound-info="detailed"
# Options: always, basic, detailed, full, never
show-logistic-robot-targets="full"
# Options: always, basic, detailed, full, never
show-player-robots="never"
# Options: always, basic, detailed, full, never
show-fire-info="full"
# Options: always, basic, detailed, full, never
show-sticker-info="full"
# Options: always, basic, detailed, full, never
show-map-generator-info="full"
# Options: always, basic, detailed, full, never
show-decorative-names="full"
# Options: always, basic, detailed, full, never
allow-increased-zoom="full"

# [multiplayer-lobby]
name=""
description=""
# Options: true, false
visibility-public="true"
# Options: true, false
visibility-lan="true"
max-players="0"
# Options: true, false
ignore-player-limit-when-returning="false"
max-upload-in-kilobytes-per-second="0"
password=""
tag-list=""
afk-auto-kick="0"
# Options: true, false, admins-only
allowed-commands="admins-only"
# Options: true, false
only-admins-can-pause="true"
# Options: true, false
autosave-only-on-server="true"
# Options: true, false
non-blocking-saving="true"
# Options: true, false
verify-user-identity="true"

# [interface]
# Options: true, false
system-ui-scale="true"
custom-ui-scale="1.000000"
tooltip-delay="0.040000"
output-console-delay="1200"
train-stop-label-angle="0.085526"
# Options: true, false
force-default-logistic-filter-count-to-one="false"
# Options: true, false
autosort-inventory="true"
# Options: true, false
research-finished-stops-game="false"
# Options: true, false
use-item-groups="true"
# Options: true, false
use-item-subgroups="true"
# Options: true, false
use-version-filter-in-browse-games-gui="true"
# Options: true, false
play-sound-for-chat-messages="true"
# Options: true, false
fuzzy-search-enabled="false"
# Options: true, false
show-minimap="true"
# Options: true, false
show-tips-and-tricks="true"
# Options: true, false
show-tutorial-notifications="true"
# Options: true, false
show-turret-radius-when-blueprinting="false"
# Options: true, false
show-item-labels-in-cursor="true"
# Options: true, false
show-mod-owners-in-tooltips="true"
# Options: true, false
show-rail-block-visualization="true"
# Options: true, false
show-missing-logistic-network-icon="true"
# Options: true, false
show-grid-when-paused="true"
# Options: true, false
show-inserter-arrows-when-selected="true"
# Options: true, false
show-inserter-arrows-when-detailed-info-is-on="false"
# Options: true, false
show-pump-arrows-when-detailed-info-is-on="true"
# Options: true, false
show-mining-drill-arrows-when-detailed-info-is-on="true"
# Options: true, false
show-combinator-settings-when-detailed-info-is-on="false"
debug-font-size="18"

# [graphics]
lights-render-quality="0.250000"
multisampling-level="0"
preferred-screen-index="255"
screenshots-queue-size="10"
screenshots-threads-count="1"
cache-sprite-atlas-count="1"
max-texture-size="0"
max-secondary-texture-size="0"
max-threads="16"
# Options: high, normal, low, very-low
graphics-quality="normal"
# Options: true, false
full-screen="true"
# Options: true, false
show-smoke="true"
# Options: true, false
show-clouds="true"
# Options: true, false
show-decoratives="true"
# Options: true, false
show-item-shadows="true"
# Options: true, false
show-inserter-shadows="true"
# Options: true, false
force-opengl="false"
# Options: true, false
cache-sprite-atlas="false"
# Options: true, false
texture-streaming="false"
# Options: true, false
thread-sprite-loading="true"
# Options: true, false
v-sync="true"
# Options: true, false
tree-sprite-mipmaps="true"
# Options: true, false
trilinear-filtering="true"
# Options: true, false
shader-enabled="true"
# Options: true, false
atlas-specialization="true"
# Options: true, false
separate-lower-object-atlas="false"
# Options: true, false
atlas-packing-optimization="true"
# Options: true, false
low-quality-sprite-rotation="false"
# Options: true, false
skip-vram-detection="false"
# Alpha masks are loaded as single channel textures. This may cause problems on some configurations.
# Options: true, false
single-channel-textures="true"
# Options: true, false
halting-rending-when-minimized="true"
# Options: true, false
runtime-sprite-reload="false"
# Options: all, high, medium, low
video-memory-usage="high"
# Options: false, true, auto
texture-compression="false"


##################################################
#!!!!!!!!!!! map-settings start here !!!!!!!!!!!!!
##################################################
[map-settings]
max_failed_behavior_count = 3

[difficulty_settings]
recipe_difficulty = 0
technology_difficulty = 0
technology_price_multiplier = 1

[enemy_evolution]
destroy_factor = 0.002
enabled = true
pollution_factor = 1.5e-05
time_factor = 4.0e-06

[enemy_expansion]
building_coefficient = 0.1
enabled = true
enemy_building_influence_radius = 2
friendly_base_influence_radius = 2
max_colliding_tiles_coefficient = 0.9
max_expansion_cooldown = 216000
max_expansion_distance = 7
min_base_spacing = 3
min_expansion_cooldown = 14400
neighbouring_base_chunk_coefficient = 0.4
neighbouring_chunk_coefficient = 0.5
other_base_coefficient = 2.0
settler_group_max_size = 20
settler_group_min_size = 5

[path_finder]
cache_accept_path_end_distance_ratio = 0.15
cache_accept_path_start_distance_ratio = 0.2
cache_max_connect_to_cache_steps_multiplier = 100
cache_path_end_distance_rating_multiplier = 20
cache_path_start_distance_rating_multiplier = 10
direct_distance_to_consider_short_request = 100
enemy_with_different_destination_collision_penalty = 30
fwd2bwd_ratio = 5
general_entity_collision_penalty = 10
general_entity_subsequent_collision_penalty = 3
goal_pressure_ratio = 2
ignore_moving_enemy_collision_distance = 5
long_cache_min_cacheable_distance = 30
long_cache_size = 25
max_clients_to_accept_any_new_request = 10
max_clients_to_accept_short_new_request = 100
max_steps_worked_per_tick = 100
min_steps_to_check_path_find_termination = 2000
negative_cache_accept_path_end_distance_ratio = 0.3
negative_cache_accept_path_start_distance_ratio = 0.3
short_cache_min_algo_steps_to_cache = 50
short_cache_min_cacheable_distance = 10
short_cache_size = 5
short_request_max_steps = 1000
short_request_ratio = 0.5
stale_enemy_with_same_destination_collision_penalty = 30
start_to_goal_cost_multiplier_to_terminate_path_find = 500.0
use_path_cache = true

[pollution]
_comment_min_to_diffuse_1 = "these are values for 60 ticks (1 simulated second)"
_comment_min_to_diffuse_2 = "amount that is diffused to neighboring chunk"
ageing = 1
diffusion_ratio = 0.02
enabled = true
expected_max_per_chunk = 7000
max_pollution_to_restore_trees = 1000
min_pollution_to_damage_trees = 3500
min_to_diffuse = 15
min_to_show_per_chunk = 700
pollution_per_tree_damage = 2000
pollution_restored_per_tree_damage = 500
pollution_with_max_forest_damage = 10000

[steering.default]
force_unit_fuzzy_goto_behavior = false
radius = 1.2
separation_factor = 1.2
separation_force = 0.005

[steering.moving]
force_unit_fuzzy_goto_behavior = false
radius = 3
separation_factor = 3
separation_force = 0.01

[unit_group]
max_gathering_unit_groups = 30
max_group_gathering_time = 36000
max_group_member_fallback_factor = 3
max_group_radius = 30.0
max_group_slowdown_factor = 0.3
max_member_slowdown_when_ahead = 0.6
max_member_speedup_when_behind = 1.4
max_unit_group_size = 200
max_wait_time_for_late_members = 7200
member_disown_distance = 10
min_group_gathering_time = 3600
min_group_radius = 5.0
tick_tolerance_when_member_arrives = 60
